package com.ivansan.blogfinalproject.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;


@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Comment {
    // @Id annotation is used to tell spring that this field is the primary key of the entity
    // @GeneratedValue annotation is used to tell spring that this field is auto generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    // @Column annotation is used to tell spring that this field is a column in the database
    // length attribute is used to tell spring that the maximum length of the column is 1000 characters
    @Column(length = 1000)
    private String comment;

    @JoinColumn(name = "user_id", nullable = false)
    @ManyToOne
    private User user;


    // @ManyToOne annotation is used to tell spring that this field is a many-to-one relationship with the Post entity
    // - JoinColumn annotation is used to tell spring that the field that is used to map the relationship is the post_id field in the Comment entity
    @ManyToOne
    @JoinColumn(name = "post_id", nullable = false)
    private Post post;

    @CreationTimestamp
    // @CreationTimestamp annotation is used to tell spring that this field is auto generated by the database
    private LocalDateTime createdAt;

    @UpdateTimestamp
    // @UpdateTimestamp annotation is used to tell spring that this field is auto generated by the database
    private LocalDateTime updatedAt;
}
